# -*- coding: utf-8 -*-
"""list_comprehension.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13npY8wij4HkvyrpBpjPy7pxbCeelt3jS
"""

letters=["a","b","c","ad"]
newlist=[]
for x in letters:
  if "a" in x:
    newlist.append(x)
print(newlist)

newlist=[x for x in letters if "a" in x]
newlist

"""Only accept items that are not "a"
"""

newlist=[x for x in letters if x!="a"]
newlist

"""No if statement"""

newlist=[x for x in letters]
newlist

"""with iterables"""

newlist=[x for x in range(10)]
newlist

"""Create a list of all odd numbers between 1 and 20."""

newlist=[x for x in range(20) if x%2!=0]
newlist

"""Make a list of the lengths of words in ["hello", "world", "python"]"""

lists=["hello", "world", "python"]
newlist=[len(x) for x in lists]
newlist

"""From a list of numbers, return a list of only the positive numbers"""

nlist=[1,2,-5,-9,-4,3,6,8]
newlist=[x for x in nlist if x>0]
newlist

"""Flatten this nested list: [[1, 2], [3, 4], [5]] → [1, 2, 3, 4, 5]"""

nested_list=[[1, 2], [3, 4], [5]]
flat_list=[]
for sublist in nested_list:
  # print(sublist)
  for item in sublist:
    # print(item)
    flat_list.append(item)
flat_list

"""From a sentence, return a list of all words longer than 3 characters"""

flat_list_c=[item for sublist in nested_list for item in sublist]
flat_list_c

newlist=[x for x in lists if len(x)>5]
newlist